# Change these first
owner: klentoy # Your GitHub organization or username, where this repository lives
repo: shipwreck-uptime # The name of this repository

sites:
  - name: TopCoins
    url: http://thetopcoins.com/
  - name: AList
    url: http://alistpropertygroup.com.au/

status-website:
  baseUrl: /shipwreck-uptime
  logoUrl: https://scontent.fdvo2-1.fna.fbcdn.net/v/t1.18169-9/10561614_321626321335346_3216717715787967113_n.png?_nc_cat=101&ccb=1-5&_nc_sid=973b4a&_nc_ohc=lt2qhMfz370AX-0-4_m&_nc_ht=scontent.fdvo2-1.fna&oh=17faad10e387bbda742449200f5d7060&oe=61861FC9
  name: Upptime
  introTitle: "**ShipWreckUptime Montior** It's misspelled internationally"
  introMessage: "It's not **down**, it's a feature"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
